#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : VirtualBox
Version  : 6.0.4
Release  : 1
URL      : https://download.virtualbox.org/virtualbox/6.0.4/VirtualBox-6.0.4.tar.bz2
Source0  : https://download.virtualbox.org/virtualbox/6.0.4/VirtualBox-6.0.4.tar.bz2
Summary  : Oracle VM VirtualBox
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause BSD-4-Clause BSL-1.0 CDDL-1.0 GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-2.1 Libpng MIT NPL-1.1
BuildRequires : LibVNCServer-dev
BuildRequires : SDL-dev
BuildRequires : SDL_ttf-dev
BuildRequires : acpica-unix2-bin
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-meson
BuildRequires : buildreq-qmake
BuildRequires : buildreq-scons
BuildRequires : curl-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glib-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : glu-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXrandr-dev
BuildRequires : libXtst-dev
BuildRequires : libpng-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : linux-libc-headers
BuildRequires : mesa-dev
BuildRequires : nasm
BuildRequires : openjdk
BuildRequires : openssl-dev
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(devmapper)
BuildRequires : pkgconfig(dri2proto)
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(glproto)
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pkgconfig(libcap)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libdrm_amdgpu)
BuildRequires : pkgconfig(libdrm_intel)
BuildRequires : pkgconfig(libdrm_nouveau)
BuildRequires : pkgconfig(libdrm_radeon)
BuildRequires : pkgconfig(libelf)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(opus)
BuildRequires : pkgconfig(pthread-stubs)
BuildRequires : pkgconfig(samplerate)
BuildRequires : pkgconfig(valgrind)
BuildRequires : pkgconfig(vdpau)
BuildRequires : pkgconfig(vpx)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(wayland-scanner)
BuildRequires : pkgconfig(wayland-server)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-dri2)
BuildRequires : pkgconfig(xcb-xfixes)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xvmc)
BuildRequires : pkgconfig(xxf86vm)
BuildRequires : pkgconfig(zlib)
BuildRequires : pulseaudio-dev
BuildRequires : python-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : sed
BuildRequires : xorg-server-dev
Patch1: 0001-Don-t-quit-on-unrecognized-options.patch
Patch2: 0002-Add-local-config.patch

%description
VirtualBox is a powerful PC virtualization solution allowing
you to run a wide range of PC operating systems on your Linux
system. This includes Windows, Linux, FreeBSD, DOS, OpenBSD
and others. VirtualBox comes with a broad feature set and
excellent performance, making it the premier virtualization
software solution on the market.

%prep
%setup -q -n VirtualBox-6.0.4
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
echo "VBOX_GCC_OPT=$CXXFLAGS" >> LocalConfig.kmk
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571170228
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --disable-docs \
--enable-webservice \
--enable-vde \
--enable-vnc \
--disable-kmods \
--with-makeself=/usr/bin/true
make  %{?_smp_mflags}  || source /builddir/build/BUILD/VirtualBox-6.0.4/env.sh && kmk

%install
export SOURCE_DATE_EPOCH=1571170228
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/VirtualBox
cp %{_builddir}/VirtualBox-6.0.4/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/440b8d3515e1b7ad3be48b6d26682281e368290f
cp %{_builddir}/VirtualBox-6.0.4/COPYING.CDDL %{buildroot}/usr/share/package-licenses/VirtualBox/60bf56729bf430a3bad7ca941669faebc270ba97
cp %{_builddir}/VirtualBox-6.0.4/doc/License-gpl-2.0.html %{buildroot}/usr/share/package-licenses/VirtualBox/535be0057e061710b3d819669251d9bcedc9622b
cp %{_builddir}/VirtualBox-6.0.4/doc/License-gpl-2.0.txt %{buildroot}/usr/share/package-licenses/VirtualBox/440b8d3515e1b7ad3be48b6d26682281e368290f
cp %{_builddir}/VirtualBox-6.0.4/doc/License-gpl-2.html %{buildroot}/usr/share/package-licenses/VirtualBox/c2045d00c86271d8948e417a8c8e9e0d7e636995
cp %{_builddir}/VirtualBox-6.0.4/doc/License-gpl-2.rtf %{buildroot}/usr/share/package-licenses/VirtualBox/e896c048dbbfff1582197a9b618497dc5a11caa7
cp %{_builddir}/VirtualBox-6.0.4/doc/License-gpl-2.txt %{buildroot}/usr/share/package-licenses/VirtualBox/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/VirtualBox-6.0.4/kBuild/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/VirtualBox-6.0.4/kBuild/doc/COPYING-FDL-1.3 %{buildroot}/usr/share/package-licenses/VirtualBox/e1d31e42d2a477d6def889000aa8ffc251f2354c
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Additions/3D/mesa/mesa-17.3.9/docs/license.html %{buildroot}/usr/share/package-licenses/VirtualBox/22e1aa94f7b2f13daadb99302d060b9663a4cc5b
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Additions/3D/mesa/mesa-17.3.9/src/mapi/glapi/gen/license.py %{buildroot}/usr/share/package-licenses/VirtualBox/98d051673de64cfd533ded6d75f1526f5f4f27af
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Additions/common/crOpenGL/LICENSE %{buildroot}/usr/share/package-licenses/VirtualBox/3c93e47989f34b4c87c226d1a27a4e9e98d6930d
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/AppPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/BaseTools/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/716291b5f2b61d3f09e8695d22dc8b539d8c9648
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/CryptoPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/FatBinPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/8f64265fc115a4d8a2d269a6f6518b07bb686893
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/IntelFrameworkModulePkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/IntelFrameworkPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/MdeModulePkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/MdePkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/NetworkPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/OptionRomPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/OvmfPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/PcAtChipsetPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/PerformancePkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/SecurityPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/ShellPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/SourceLevelDebugPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/StdLib/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/StdLibPrivateInternalFiles/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/EFI/Firmware/UefiCpuPkg/License.txt %{buildroot}/usr/share/package-licenses/VirtualBox/6d794cb33fdc87e0223ba861b2ffc23171745d29
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/Graphics/BIOS/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/fdeb196b87202005f0c9ee4044f6a7da68a43801
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/Network/lwip-new/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/f32e378a7ff5a691eaab216ea38ff8b080be3842
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/Network/slirp/COPYRIGHT %{buildroot}/usr/share/package-licenses/VirtualBox/ac4c40902ddc102b9e813121f016ae4667122f87
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/PC/ipxe/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/075d599585584bb0e4b526f5c40cb6b17e0da35a
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/PC/ipxe/COPYRIGHTS %{buildroot}/usr/share/package-licenses/VirtualBox/cedc99c80ddc135681756e652d55c72d89ebdfe7
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Devices/PC/ipxe/src/include/ipxe/efi/LICENCE %{buildroot}/usr/share/package-licenses/VirtualBox/ca46b2cea92edc93654b11c06c0073ec1a2e50e8
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/ExtPacks/VBoxDTrace/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/83b29742cc2bd54dc6127642cbb594b464da7221
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/ExtPacks/VBoxDTrace/onnv/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/96e18585c8e530587847bdbcf7cb0cf6758b47a2
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Frontends/Common/VBoxKeyboard/COPYING.LIB %{buildroot}/usr/share/package-licenses/VirtualBox/caeb68c46fa36651acf592771d09de7937926bb3
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Frontends/VirtualBox/shaders/COPYRIGHT %{buildroot}/usr/share/package-licenses/VirtualBox/05c888e6d0869b1fd038e8d1b4c06c5132a2354b
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/GuestHost/OpenGL/LICENSE %{buildroot}/usr/share/package-licenses/VirtualBox/3c93e47989f34b4c87c226d1a27a4e9e98d6930d
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/HostServices/SharedOpenGL/LICENSE %{buildroot}/usr/share/package-licenses/VirtualBox/3c93e47989f34b4c87c226d1a27a4e9e98d6930d
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/Installer/linux/debian/copyright %{buildroot}/usr/share/package-licenses/VirtualBox/7757411284769fe039fb41fedf7108a79f50e1db
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/RDP/client-1.8.4/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/842745cb706f8f2126506f544492f7a80dbe29b3
cp %{_builddir}/VirtualBox-6.0.4/src/VBox/RDP/client-1.8.4/licence.c %{buildroot}/usr/share/package-licenses/VirtualBox/1af8bb73ef90a4beb60832995e7eae555ebf7325
cp %{_builddir}/VirtualBox-6.0.4/src/libs/liblzf-3.4/LICENSE %{buildroot}/usr/share/package-licenses/VirtualBox/be542d9a6c0ae0ed97cef5c67961d5e5912530f2
cp %{_builddir}/VirtualBox-6.0.4/src/libs/libpng-1.2.54/LICENSE %{buildroot}/usr/share/package-licenses/VirtualBox/46868760b81cfd58f4a68b3b00bdda3274b63662
cp %{_builddir}/VirtualBox-6.0.4/src/libs/libpng-1.2.54/contrib/gregbook/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/dfac199a7539a404407098a2541b9482279f690d
cp %{_builddir}/VirtualBox-6.0.4/src/libs/libpng-1.2.54/contrib/gregbook/LICENSE %{buildroot}/usr/share/package-licenses/VirtualBox/aa4b9207aaff26bc16c562d6cd766a9eed49af1e
cp %{_builddir}/VirtualBox-6.0.4/src/libs/libpng-1.6.36/LICENSE %{buildroot}/usr/share/package-licenses/VirtualBox/e01ba244558d7a6b6729885beb54e9e561583101
cp %{_builddir}/VirtualBox-6.0.4/src/libs/libpng-1.6.36/contrib/gregbook/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/80b6f4fcbc19d7431482cba012e86f587828c1ba
cp %{_builddir}/VirtualBox-6.0.4/src/libs/libpng-1.6.36/contrib/gregbook/LICENSE %{buildroot}/usr/share/package-licenses/VirtualBox/aa4b9207aaff26bc16c562d6cd766a9eed49af1e
cp %{_builddir}/VirtualBox-6.0.4/src/libs/libxml2-2.9.4/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/3c21506a45e8d0171fc92fd4ff6903c13adde660
cp %{_builddir}/VirtualBox-6.0.4/src/libs/libxml2-2.9.4/Copyright %{buildroot}/usr/share/package-licenses/VirtualBox/3c21506a45e8d0171fc92fd4ff6903c13adde660
cp %{_builddir}/VirtualBox-6.0.4/src/libs/xpcom18a4/nsprpub/pkg/solaris/common_files/copyright %{buildroot}/usr/share/package-licenses/VirtualBox/85288a9d4f7312e9f8a3541df258fbde9ded78e8
cp %{_builddir}/VirtualBox-6.0.4/src/libs/zlib-1.2.11/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/VirtualBox/3f317fbb3e08fd99169d2e77105d562ea0e482c7
cp %{_builddir}/VirtualBox-6.0.4/src/libs/zlib-1.2.8/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/VirtualBox/3f317fbb3e08fd99169d2e77105d562ea0e482c7
cp %{_builddir}/VirtualBox-6.0.4/src/recompiler/COPYING.LIB %{buildroot}/usr/share/package-licenses/VirtualBox/5d3e5f1162be995842d7f19c3c3cac60aee9027e
cp %{_builddir}/VirtualBox-6.0.4/tools/os2.x86/nasm/v0.98.39-bird/COPYING %{buildroot}/usr/share/package-licenses/VirtualBox/c0ee836883c18af2ee1a2135d6520f0b8378ebb4
cp %{_builddir}/VirtualBox-6.0.4/tools/os2.x86/nasm/v2.08/LICENSE %{buildroot}/usr/share/package-licenses/VirtualBox/86380574b0a199fc83414c5f986fa257e5f2ceff
%make_install

%files
%defattr(-,root,root,-)
